variables:
  StorageAccountName: <storage-account-name>
  StorageAccountUrl: https://<storage-account-name>.blob.core.windows.net/
  ContainerName: <landing-container-name>
  AzureOpenAiEndpoint: https://<open-ai-service-name>.openai.azure.com/
  AzureOpenAiEmbeddingDeploymentName: <embedding-deployment-model-deployment-name>
  AzureOpenAiModelName: <embedding-deployment-model-name>
  AzureOpenAiModelDimensions: 1536
  SearchEndpoint: https://<azure-ai-search-service-name>.search.windows.net
  AzureAIServicesEndpoint: https://<azure-ai-cognitive-service-name>.cognitiveservices.azure.com/
  IndexName: <azure-ai-search-index-name>
  TestQuery: "What is best phone for gaming?"
  IndexerInterval: "PT1H"
  SubscriptionId: <azure-subscription-id>
  ResourceGroupName: <resource-group-name>
  use_ocr: false
  use_document_layout: true
